# Generated by Django 4.2.7 on 2023-11-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliderfield')),
                ('sale', models.IntegerField()),
                ('text_para', models.TextField(max_length=250)),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
