# Generated by Django 4.2.7 on 2023-12-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_colour', models.CharField(max_length=100)),
                ('pdt_size', models.CharField(max_length=100)),
                ('pdt_description', models.TextField(max_length=250)),
                ('pdt_image1', models.ImageField(upload_to='detail_img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
