# Generated by Django 4.2.7 on 2023-12-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_productdetailview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailview',
            name='pdt_size',
        ),
    ]
